version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8080:8080"
    command: python3 -m gunicorn -b 0.0.0.0:8080 app:server > /app/logs/flask_log/0.log 2>&1

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app