services:
  predictiveml:
    container_name: predictiveml
    build: ./flask_app
    ports:
      - "8000:8000"
    volumes:
      - ./flask_app/results:/flask_app/results
      - ./flask_app/logs:/flask_app/logs
      - ./flask_app/models:/flask_app/models
      - ./flask_app/end_date_time_record.txt:/flask_app/end_date_time_record.txt
      - ./flask_app/spaces_prediction_data:/flask_app/spaces_prediction_data
      - ./flask_app/app.py:/flask_app/app.py
